#!/usr/bin/env bash

export CONTECO_LABEL="stack.kz - ContEco"
export CONTECO_DESCRIPTION="KZ Stack image, consisting of Kafka and Zookeeper."

export CONTECO_TYPE="stack"
export CONTECO_NAME="kz"
export CONTECO_TAG="v1.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
